### ISSUE TITLE
API

### ISSUE THREAD

**Issue by neurosisone** [ponguincom/ip-address-card-widget#1]
I really like the IP address card concept that you created, however, your API for the info that directs to your website (api.ponguin.com/api/ip) is not in that directory. can you post the API cope too :-) The reason I say concept I've never used it.

**Comment by fanatikhamsi** [comment]
Hi, 
My api is offline for 2 months. I changed api to public(http://ip-api.com/docs/api:json : 150 requests per minute). you can use the plugin.
If you change the api another service, you can with readData = function () in ip-address-card.js
Good lock

**Comment by neurosisone** [comment]
Thanks for the rapid response and the solution I appreciate it!
